// Mock customer data - in a real app, this would come from a database
export const customers = [
    {
        id: 1,
        name: "John Smith",
        email: "john.smith@example.com",
        status: "current",
        balance: 0,
        lastPayment: "2024-01-15",
    },
    {
        id: 2,
        name: "Sarah Johnson",
        email: "sarah.johnson@example.com",
        status: "overdue",
        balance: 1250.0,
        overdueAmount: 1250.0,
        dueDate: "2023-12-15",
        daysPastDue: 23,
        lastPayment: "2023-11-10",
    },
    {
        id: 3,
        name: "Mike Davis",
        email: "mike.davis@example.com",
        status: "current",
        balance: 500.0,
        lastPayment: "2024-01-10",
    },
    {
        id: 4,
        name: "Emily Wilson",
        email: "emily.wilson@example.com",
        status: "overdue",
        balance: 2100.0,
        overdueAmount: 2100.0,
        dueDate: "2023-12-20",
        daysPastDue: 18,
        lastPayment: "2023-10-15",
    },
    {
        id: 5,
        name: "Robert Brown",
        email: "robert.brown@example.com",
        status: "overdue",
        balance: 750.0,
        overdueAmount: 750.0,
        dueDate: "2023-12-10",
        daysPastDue: 28,
        lastPayment: "2023-09-20",
    },
]
